### ISSUE TITLE
Computed property fields is already defined as a prop

### ISSUE THREAD

**Issue by hawkleaf** [jecovier/vue-json-excel#11]
That's the error I'm getting in the console on load. I can't open the downloaded file in drive or on mac preview either.
```
json_fields: {
        reference_number: 'String',
        location: 'String',
        amount: 'Number',
        severity: 'String',
        original_part: 'String',
        component: 'String',
        component_manufacturer: 'String',
        smc_replacement: 'String',
      },
      json_data: [],
      json_meta: [[{ "key": "charset", "value": "utf-8"}]]
```
Those are the settings I'm using, the json_data is later populated.

**Comment by jecovier** [comment]
there is a problem with the downloaded file in windows, Maybe it's the same problem. could you open the downloaded file in a text editor? is it populated?

**Comment by Crestop** [comment]
That's the error I'm getting in the console on load. I can export file into excel file but the error is still not yet resolved.

**Comment by jecovier** [comment]
@hawkleaf @Crestop hi, there is a new version that has no console error. thanks for the comments.

**Comment by michael-caraiani** [comment]
Have the same issue in console 'Computed property fields is already defined as a prop'

**Comment by claymore07** [comment]
> Have the same issue in console 'Computed property fields is already defined as a prop'

did you solve this problem? I getting it to!
