### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by angiespencer** [jecovier/vue-json-excel#110]
Hello,

It seems that the download-excel tag is not working in IE. It works fine in Chrome, but when I click on it in IE, nothing happens. Any advice on how to get this working would be appreciated!

**Comment by jecovier** [comment]
@angiespencer Hi, sorry for the late response. Basically this component use a Blob object to create the download file and download.js library to trigger the download process. Download.js and Blob type aren't  support in IE9 or below.
