### ISSUE TITLE
版本0.2.98导出的CSV数据都带双引号和等号

### ISSUE THREAD

**Issue by Blueria** [jecovier/vue-json-excel#114]
版本：0.2.98
vue版本：2.6.10

源数据：
![image](https://user-images.githubusercontent.com/7038130/63249067-42538500-c29b-11e9-9bf0-bda29645d97a.png)

导出后：
![image](https://user-images.githubusercontent.com/7038130/63249128-61521700-c29b-11e9-8c9b-3f399c2bf79e.png)

等号和双引号是什么鬼？

**Comment by jecovier** [comment]
@Blueria 嗨，您好，很抱歉收到您的延迟回复...这是一个经常发生的问题，导致Excel修复...将在下次更新中解决

**Comment by jecovier** [comment]
Hi, there is a new update that fix this problem
