### ISSUE TITLE
[Vue warn]: The computed property "fields" is already defined as a prop.

### ISSUE THREAD

**Issue by biigpongsatorn** [jecovier/vue-json-excel#115]
I have use props `export-fields` but still get [Vue warn]

```vue
         <DowloadCSV
          :data="data"
          :export-fields="jsonFields"
          :meta="jsonMeta"
          class="dowload-btn"
          type="csv"
        >
          <b-icon
            icon="download"
            size="is-small"
          />
          Download CSV
        </DowloadCSV>
```

**Comment by linkcardcto** [comment]
Same problem. i dont know how to use that 

          :export-fields=

Expects an object, makes no sense

**Comment by jecovier** [comment]
Hi there, Sorry for the late response... I test it with the current version of the component but it works for me. Maybe you could provide me the console output.

Maybe I have to update the README file with a better explanation of how to use it. The way to use it is:

```
:export-fields="{
    'Human friendly name': '_name_field_from_json',
    'user's last name': '_last_name_text'
}"
```

**Comment by heiqs** [comment]
I am also facing this issue using 0.3.0 version:

`<download-excel :data="items" :exportFields="export_headers" worksheet="My Worksheet" name="filename.xls">`

**Comment by jecovier** [comment]
hi @heiqs, could you post the console error and export_headers content?
