### ISSUE TITLE
conflict: title is useful attribute

### ISSUE THREAD

**Issue by jeffster9** [jecovier/vue-json-excel#118]
Just ran into an annoyance where I wanted to set a title...
`<download-excel title="Download as Excel">Download</download-excel>`
but I also want to use the title prop...
`<download-excel :title="My Document Header">Download</download-excel>`
Maybe add another prop called 'header' that does the same thing as the 'title' prop?

**Comment by jecovier** [comment]
@jeffster9 sorry for the late response. Yeah, you're rigth, maybe I can use something like:
```js
this.header || this.$attrs.title
```
It will be on the next version
