### ISSUE TITLE
Not working if big data

### ISSUE THREAD

**Issue by czalexpic** [jecovier/vue-json-excel#12]
Hello!

I think problem by window.location.href - length
https://stackoverflow.com/questions/15090220/maximum-length-for-url-in-chrome-browser
(test windows 10, chrome v.62...)

Thx!

**Comment by jecovier** [comment]
hi @czalexpic thanks for the information. It seems that there is no workaround for this issue, at least not from a JS perspective. The library now use downloadjs to get the file, I hope they find a solution.
