### ISSUE TITLE
Issue with data type that is being exported to excel

### ISSUE THREAD

**Issue by nillamahesh** [jecovier/vue-json-excel#122]
On exporting/downloading data into excel sheet, the data in excel is shown as string even though I am passing one of the field value as Number.

In below amount field, transactionAmount is of type Number but in excel I am getting this amount as String. Please find below screenshot of the amount field in excel.

Amount : "transactionAmount"

![excel](https://user-images.githubusercontent.com/20710637/73012808-10fc5980-3de5-11ea-865b-b954a95c1086.JPG)

Please let me know if there is a fix for this issue ?

Thanks,
Mahesh

**Comment by jecovier** [comment]
Hi there, I update the component to fix this issue. Sorry for the late response.
