### ISSUE TITLE
csv file has "=" at the beginning and "" at the end of each field

### ISSUE THREAD

**Issue by DedicatedManagers** [jecovier/vue-json-excel#127]
```
Date,FirstName
"=""2020-03-17T19:27:47.289771Z""","=""Terry"""
"=""2020-03-17T15:31:52.9888394Z""","=""Terry"""
```

**Comment by jny986** [comment]
I came across this also while creating CSV import for Xero and discovered that they made the change without notifying of breaking changes.
[Commit Making Changes](https://github.com/jecovier/vue-json-excel/commit/6c167f270d8a16c47f2c146efd4cedbaa8ca97c9#diff-9b329de2b5c9f5228a7b68007639a642)
There should be a prop for determining if the csv values should be escaped or not

**Comment by lauzonryd** [comment]
I'm getting this same issue.  Has this been resolved yet?

**Comment by jecovier** [comment]
@jny986 thanks a lot for your PR. It is merged now, I'm updating this component so it will be deployed in the next version. Sorry @DedicatedManagers for the late response.
