### ISSUE TITLE
Header shown in downloaded excel is provided dataType in 0.0.8

### ISSUE THREAD

**Issue by nafiulislamtony** [jecovier/vue-json-excel#13]
Just execute the example provided in ReadMe - it'll show String/Number (means given Data Type for columns) in the header of downloaded excel file.

**Comment by ryatziv** [comment]
Yep, I see that too.
For now I've changed my mapping to 
```
json_fields: {
        'name': 'name',
        'amount': 'amount'
      },
```

**Comment by jecovier** [comment]
@nafiulislamtony the readme file was updated to clarify this. The json_fieds works like:
```
json_fields: {
        'label': 'field',
        'Second Label': 'nested.field'
      },
```
I think is better that way, so you can change how the output file is presented.
