### ISSUE TITLE
i cant use fetch complete request

### ISSUE THREAD

**Issue by roborock** [jecovier/vue-json-excel#133]
when i wait async await request after i return data but  nothing happened  no error anything. show...

please help me

**Comment by jecovier** [comment]
hey @roborock I'll try to help you when I get home. Could you paste the code of your request?

**Comment by roborock** [comment]
i changed package for excel print thank you.

________________________________
Gönderen: Jose Javier Espinoza <notifications@github.com>
Gönderildi: 12 Ekim 2020 Pazartesi 19:55
Kime: jecovier/vue-json-excel <vue-json-excel@noreply.github.com>
Bilgi: roborock <bbs61@hotmail.com.tr>; Mention <mention@noreply.github.com>
Konu: Re: [jecovier/vue-json-excel] i cant use fetch complete request (#133)


hey @roborock<https://github.com/roborock> I'll try to help you when I get home. Could you paste the code of your request?
