### ISSUE TITLE
企业微信导出Excel报错

### ISSUE THREAD

**Issue by Miazzy** [jecovier/vue-json-excel#136]
![截屏2020-10-27 16 59 08](https://user-images.githubusercontent.com/18606977/97279255-bc0ad980-1875-11eb-9496-8bb21b787f99.png)

**Comment by Miazzy** [comment]
企业微信导出时报错，无法访问该网页，浏览器导出Excel时，正常运行

**Comment by jecovier** [comment]
Hi @Miazzy, I don't know how WeChat works but it seems to me that the WeChat browser doesn't support (or doesn't allow) the blob url that is generated by the component.

**Comment by Miazzy** [comment]
Hi @jecovier Thanks
