### ISSUE TITLE
CSV file format is not good

### ISSUE THREAD

**Issue by AbingPj** [jecovier/vue-json-excel#137]
When im download xls file it looks good. and arrange like this.

![image](https://user-images.githubusercontent.com/38340100/98892745-e9918d00-24db-11eb-960d-f149d951fe06.png)

but when i try use CSV, the format is not good. see this.

![image](https://user-images.githubusercontent.com/38340100/98892900-442ae900-24dc-11eb-8fb6-f2761f8f6151.png)

Is this have another way to fix this? The CSV file is needed of our client

**Comment by jecovier** [comment]
Hi @AbingPj I don't know if there is a way to style a csv... let me investigate

**Comment by jecovier** [comment]
Hi again, It seems to me that there's no way to add styles to a csv file. I read a lot of documentations but found nothing about "styling"... If you know some way please reopen this issue
