### ISSUE TITLE
Support for customizing the filename to export?

### ISSUE THREAD

**Issue by kyrie-z** [jecovier/vue-json-excel#138]
I want to implement a different file name each time I export the file. Is it supported now or what should I do if it is?

**Comment by kyrie-z** [comment]
version now :0.3.0

**Comment by jecovier** [comment]
you can use the "name" prop, maybe associate it to a variable that change every time you download the file... but how you now when the file is downloaded :thinking: ... maybe add a "downloaded" event... or maybe listen to  @click event?

**Comment by kyrie-z** [comment]
Thanks for your answer. @jecovier 
I've done. :smile:;but I have a question,How do I merge column cells?

**Comment by jecovier** [comment]
like colspan? I'm affraid that's not posible right now. In CSV files there is no way to do it, but maybe in XLS files I could add a property for headers... I'll try it when I have some free time
