### ISSUE TITLE
Extra prompt in Excelsheet

### ISSUE THREAD

**Issue by smaharj1** [jecovier/vue-json-excel#20]
Thanks for the lib!

When I try to open the excel file after downloaded, it always says

"The file format and extension of 'filename.xls" don't match. The file could be corrupted or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?"

I tried it in the origin code from Stackoverflow that you referred and it also shows the same message. Is there a way to get rid of it?

**Comment by jringeisen** [comment]
Same exact thing here. I also get a fuzzy text when the excel sheet opens.

**Comment by jecovier** [comment]
Hi @smaharj1, it's an issue with the recent versions of Microsoft Office, they doesn't accept xml files as native format. It's not posible to avoid that message right now, maybe implementing a xlsx file generator. Sadly, at this moment I don't have the time to do that change :disappointed:

**Comment by beargie** [comment]
Requesting bump, this seems like a major issue since the entire point of the package is to export to excel. If you don't plan to fix it soon please update the readme to save people the trouble of finding this error out after integration...

**Comment by jecovier** [comment]
@beargie you're right, I add the message in the new Readme file to ensure that the people know about this issue.

**Comment by romalev** [comment]
bumped into this one as well. @jecovier - any potential plans on fixing this one in the near future ? Thanks in advance.

**Comment by dottenbr** [comment]
We would also appreciate if this gets fixed

**Comment by fguespe** [comment]
no news here

**Comment by jecovier** [comment]
Sadly there is no way to avoid this, it's an excel security measure. The only solution is to export to xlsx, but that means to import a bunch of js code to process and compress the data to xlsx format in client side. I try to avoid that in order to keep this component as a lite as posible.
