### ISSUE TITLE
CSV Export Won't Escape Commas

### ISSUE THREAD

**Issue by DrLongGhost** [jecovier/vue-json-excel#25]
The CSV export feature won't escape commas within the data and thus is pretty badly broken.

Escaping in CSVs works as follows:

1.  If the value contains a comma, newline or double quote, then the String value should be returned enclosed in double quotes.
2. Any double quote characters in the value should be escaped with another double quote.
3. If the value does not contain a comma, newline or double quote, then the String value should be returned unchanged.

I have this sorted locally and will generate a PR for the fix momentarily.

**Comment by DrLongGhost** [comment]
https://github.com/jecovier/vue-json-excel/pull/26

**Comment by jecovier** [comment]
@DrLongGhost thank you for your update!
