### ISSUE TITLE
json_data returns value of 'undefined'

### ISSUE THREAD

**Issue by rubenmarin** [jecovier/vue-json-excel#30]
Tested with the sample data and the file shows correct headers but row data for each column prints out 'undefined'

```
name,city,country,birthdate,amount
undefined,undefined,undefined,undefined,undefined
```

**Comment by johndatserakis** [comment]
Hey bud - was having the same issue - looked at a few of the other issues here and came across this solution for another separate issue: https://github.com/jecovier/vue-json-excel/issues/13.

Basically, you don't use `string` or `number` as values for the `json_fields` properties - but rather just repeat the property name as the value. Weird, I know. And I don't know why that's happening, I may look into that later. For now, adjust the example to this:

```js
json_fields: {
  'name': 'name',
  'city': 'city',
  'country': 'country',
  'birthdate': 'birthdate',
  'amount': 'amount'
}
```

**Comment by leandrodlm** [comment]
Happened here as well, thank you @johndatserakis

**Comment by jecovier** [comment]
@rubenmarin I updated the Readme file with the correct documentation about how to use the json_fields.

**Comment by jecovier** [comment]
@johndatserakis thaks for the answer, I update the readme file
