### ISSUE TITLE
Add Custom Info Above Data Grid

### ISSUE THREAD

**Issue by snow-drop** [jecovier/vue-json-excel#35]
Good day. Can this component be able to add custom information above the data grid? Like

```
User: Kosaki Onodera
Age: 17
Gender: Female
```
Thanks in advance. :)

**Comment by jecovier** [comment]
Hi there, sorry for the late response, you can add a title text in the generated file using the title prop. Although this is one line text, maybe it helps you.

**Comment by jecovier** [comment]
Hi @snow-drop I update to the version 0.1.8 now support multiple titles, used as follows:
```html
<vueJsonExcel
      type = "csv"
      :title = '["user: Kosaki Onodera","Age: 17","Gender: Female"]'
      name="data.csv"
      :data = "datos"
      :fields = "fields">
      CSV FILE
    </vueJsonExcel>
```
