### ISSUE TITLE
Add an extra line to your CSV file to tell Excel what the separator is.

### ISSUE THREAD

**Issue by AleksandrGol** [jecovier/vue-json-excel#38]
# What?
Edit line 108:
```
var csvData = 'sep=,\r\n'
```
This will tell Excel to use the "," character as separator for the next lines. This first line is considered an instruction and not shown in your Excel sheet.

https://github.com/jecovier/vue-json-excel/blob/b8aaaed94f8757cd62f911c2432e3a6f16f500a3/JsonExcel.vue#L114

**Comment by jecovier** [comment]
Hello @AleksandrGol, thanks for the suggestion!. I read about it and this seems to work only on excel. I think it would be great if it was an standard option, I prefer keep the line as it is for now.
