### ISSUE TITLE
Urgent Help Needed

### ISSUE THREAD

**Issue by Timtech4u** [jecovier/vue-json-excel#39]
I did a correct import of the vue-json-excel library and also did:
import JsonExcel from 'vue-json-excel'

  component: {
    'downloadExcel': JsonExcel
  }, 

But here's the error I get on the console: 

Unknown custom element: <download-excel> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by gusehr** [comment]
Hi @Timtech4u.

I think you can use the import inside the Vue component on your main.js or app.js.
```
import Vue from 'vue'
import JsonExcel from 'vue-json-excel'

Vue.component('downloadExcel', JsonExcel);
```

**Comment by Timtech4u** [comment]
Thanks, It works :-D

**Comment by gusehr** [comment]
Hi @Timtech4u 

Can you close de issue?
See ya.
