### ISSUE TITLE
Null values are printed as null

### ISSUE THREAD

**Issue by reinerBa** [jecovier/vue-json-excel#41]
I am wondering why null is interpreted as the string value "null"

```javascript
jsonData = [
  {
    "Name1":  "John",
    "Name2": null
  },
  {
    "Name1":  "Doo",
    "Name2": null
  }
]
```

Results in the excel file
![unbekannt](https://user-images.githubusercontent.com/4329883/37826860-730641e2-2e95-11e8-9e36-21b0f7d65332.png)

I did a workaround but this shouldn't be the final solution right?

```javascript
    computed: {
      json_data () {
          return this.jsonData.map(e => {
              let tmp = {}
              for (let k in e) {
                  tmp[k] = e[k] === null ? '' : e [k]
              }
              return tmp
          })
      }
    }
```

**Comment by jecovier** [comment]
Hi @reinerBa sorry for the super late response, now by default all the undefined or null values are converted to blank space. There is a new prop called default-value that allows you to set a fallback value when the data is undefined or null.
