### ISSUE TITLE
Error: key.split is not a function

### ISSUE THREAD

**Issue by gusehr** [jecovier/vue-json-excel#42]
Hi @jecovier 

I'm getting this error when I install the 0.2.4 version.
`key.split is not a function`

I see that the current master is different from the downloaded node_module source.

Can you check the npm published component?

Thanks in advance.

**Comment by fathan** [comment]
same problem with me, @gusehr

**Comment by jecovier** [comment]
Hi @gusehr , @fathan thanks for the comments. 
I update the npm version with the github code. I've tested, now it's working.
¡Thank you for the help!
