### ISSUE TITLE
error in explorer, var fileName error

### ISSUE THREAD

**Issue by iruizeguilaz** [jecovier/vue-json-excel#46]
There is an error that only happens in explorer.

In the JonExcel.vue the method download has a parameter named fileName but it is used later on as filename (pay atention to the n that is in lowercase)  and this provokes an error in explorer

best regards

**Comment by jecovier** [comment]
Hello @iruizeguilaz sorry for the late response again. The new version don't use fileName I tested on explorer and export the file without a problem. Please let me know if the problem persist.
