### ISSUE TITLE
How I can to get a child value

### ISSUE THREAD

**Issue by iruizeguilaz** [jecovier/vue-json-excel#47]
I have tried the export to excel I do not know why but I am not able to get child baules and if it it is an usie or it just me

2 examples:

if I put the example of your wiki I get the following:

   json_meta: [
              [{
                  "key": "charset",
                  "value": "utf-8"
              }]
          ],
          json_fields: {
            'Complete name': 'name',
            'City': 'city',
            'Telephone': 'phone.mobile',
            'Telephone 2' : {
                field: 'phone.landline',
                callback: (value) => {
                    return `Landline Phone - ${value}`;
                }
            },
        },
        json_data: [
            {
                'name': 'Tony Peña',
                'city': 'New York',
                'country': 'United States',
                'birthdate': '1978-03-15',
                'phone': {
                    'mobile': '1-541-754-3010',
                    'landline': '(541) 754-3010'
                }
            },
            {
                'name': 'Thessaloniki',
                'city': 'Athens',
                'country': 'Greece',
                'birthdate': '1987-11-23',
                'phone': {
                    'mobile': '+1 855 275 5071',
                    'landline': '(2741) 2621-244'
                }
            }
        ]

name | city | phone.mobile | [object Object]
-- | -- | -- | --
undefined | undefined | undefined | undefined
undefined | undefined | undefined | undefined

------------------------------------------
if I use this another definition 

json_fields: {
            'name': 'name',
            'city': 'his city',
            'phone.mobile': 'mobile',
            },

I get:

name | his city | mobile
-- | -- | --
Tony Peña | New York | undefined
Thessaloniki | Athens | undefined

------------------------------------------------

So the wa it works for me is different to the example. I have to put the name in the json at the left and the label in the right. And I am not able to get a child like phone.mobile

**Comment by jecovier** [comment]
Hello @iruizeguilaz sorry for the super late response, I check the example and works perfectly, you can see a live demo here https://codesandbox.io/s/547k454o94 
please tell me if you still have this problem.
