### ISSUE TITLE
The computed property "fields" is already defined as a prop.

### ISSUE THREAD

**Issue by paulmeller** [jecovier/vue-json-excel#48]
I'm getting "The computed property "fields" is already defined as a prop." warning in Google Chrome.

**Comment by Jeffrey-Kimani** [comment]
Same issue here mine doesn't even download the file on chrome

**Comment by paaysay** [comment]
I am also facing the same issue. Whats the solution for this?

**Comment by jombard** [comment]
I think there is a conflict with another component here. When I change the fields prop name to something else I don't get the warning. This would probably be a breaking change so not sure how to proceed. Any ideas?

**Comment by abnerwang0991** [comment]
I am also facing the same issue. 
I guess the problem is caused by vee-validator, becuase it has 'fields' property.

**Comment by pudjamansyurin** [comment]
same with me, no solution yet?

**Comment by pudjamansyurin** [comment]
the solution for me, just hack the core, then find keyword 'fields' replace it to anything you want, ex 'json_fields'

**Comment by niravshah** [comment]
For me this was happening because I was using vee-validate. You can configure vee-validate to use a different name for the fieldsbag using the below syntax

```
Vue.use(VeeValidate, {
   fieldsBagName: 'vvFields'
});
```

**Comment by jecovier** [comment]
hey guys, I see this is a frequent problem so I made a little change that don't breaks backward compatibility. "fields" is no longer a required prop and you can use either "fields", "export-fields" or "exportFields" to define the data you want to export. I hope this fix this issue, let me know otherwise. thank you for your help

**Comment by higbdesign** [comment]
> hey guys, I see this is a frequent problem so I made a little change that don't breaks backward compatibility. "fields" is no longer a required prop and you can use either "fields", "export-fields" or "exportFields" to define the data you want to export. I hope this fix this issue, let me know otherwise. thank you for your help

Hi,
if I don't want to set the field prop (because I want export all the fields) how can I change the prop name?

**Comment by ronelvcabrera** [comment]
> hey guys, I see this is a frequent problem so I made a little change that don't breaks backward compatibility. "fields" is no longer a required prop and you can use either "fields", "export-fields" or "exportFields" to define the data you want to export. I hope this fix this issue, let me know otherwise. thank you for your help

tried "export-fields" and "exportFields" and still having this. Tried change fieldsBagName as specified but vee validate shows error.

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
was useful thanks

**Comment by juanlopezdev** [comment]
> hey guys, I see this is a frequent problem so I made a little change that don't breaks backward compatibility. "fields" is no longer a required prop and you can use either "fields", "export-fields" or "exportFields" to define the data you want to export. I hope this fix this issue, let me know otherwise. thank you for your help

Hi, I replace "fields" with "export-fields" or "exportFields" but I still get the same error message.

**Comment by imsyuan** [comment]
> > hey guys, I see this is a frequent problem so I made a little change that don't breaks backward compatibility. "fields" is no longer a required prop and you can use either "fields", "export-fields" or "exportFields" to define the data you want to export. I hope this fix this issue, let me know otherwise. thank you for your help
> 
> Hi, I replace "fields" with "export-fields" or "exportFields" but I still get the same error message.

Here is the solution for me.

```
import Vue from 'vue'
import VeeValidate from 'vee-validate'

Vue.use(VeeValidate, {
  inject: true,
  fieldsBagName: 'veeFields'
});
```

[https://github.com/bootstrap-vue/bootstrap-vue/issues/1270#issuecomment-404723914](https://github.com/bootstrap-vue/bootstrap-vue/issues/1270#issuecomment-404723914)
