### ISSUE TITLE
 Provides an interface for obtaining data when the download button is clicked

### ISSUE THREAD

**Issue by kinnylee** [jecovier/vue-json-excel#51]
My data is huge

**Comment by djdemarco** [comment]
I agree to this.  It could also be a custom function that will be called just before the generate() function and inside the function we can call another function that will fetch our data.  This is especially useful for server-side paginated data with search/filter applied, wherein only the current set of data is displayed but upon export, we need to retrieve the complete data set of the search/filter result.

**Comment by jecovier** [comment]
So the function it's call when I clik the button, fetch or transform the data, return the json object and it's downloaded. Sounds great!

**Comment by jecovier** [comment]
Hey guys, I made an update that implements a fetch prop that receive a callback function. If not data is set, the function is executed before the downloas proccess. It works with async... await so you can run http requests.

If you have a better solution please let me know.

**Comment by rjimenezg** [comment]
Hello! Could you give us an example of how to implement fetch? Another question, but I don't know if I should open a topic, is there a way to include images to the excel?

**Comment by jecovier** [comment]
Sure, here are use case:

```js
<template>
  <div id="app">
    
    <hr>
    <h2>Fetch Example</h2>
    <downloadexcel
      class = "btn"
      :fetch   = "fetchData"
      :fields = "json_fields"
      type    = "csv">
      Download Excel
    </downloadexcel>
  </div>
</template>

<script>
import downloadexcel from "vue-json-excel";
import axios from 'axios';

export default {
  name: "App",
  components: {
    downloadexcel,
  },
  data(){
    return {
      json_fields: {
        'Complete name': 'name',
        'Date': 'date',
      },
    }
  }, //data
  methods:{
    async fetchData(){
      const response = await axios.get('https://holidayapi.com/v1/holidays?key=a4b2083b-1577-4acd-9408-6e529996b129&country=US&year=2017&month=09');
      return response.data.holidays;
    },
  }
};
</script>
```
