### ISSUE TITLE
Suggession: create a default prop to set a default value of field if the field is undefined

### ISSUE THREAD

**Issue by omkardusane** [jecovier/vue-json-excel#54]
Output Excel containing undefined does not look good, Can we have a prop in the component to set the default value , foe ex. "-" or "" or "N/A"

**Comment by jecovier** [comment]
@omkardusane hello, sorry for the late response... I added a new prop called default-value (defaultValue) that allows you to define a string with the fallback value in case a row doesn't have a field. By default used a blank space as default value.

Thanks for the suggestion!

**Comment by omkardusane** [comment]
Thanks @jecovier !
