### ISSUE TITLE
support custom data type

### ISSUE THREAD

**Issue by zgq456** [jecovier/vue-json-excel#61]
once a cell is 4 / 9, I'd like to show 4 / 9, just as text , but it  will be  parsed as  date, showing 2018/4/9, 
I suggest to extend the fields  paramter to change json value from string to  json. 
current: 
```
myFields: {
  'Bussiness Text' : 'businessText'
}
```

suggestion:
```
myFields: {
  'Bussiness Text' : {'businessText', '\@' }
}
```
after that, in the JsonExcel.vue， add corresponding style to table cell. 
```
xlsData += '<td style="mso-number-format:\@;">' + item[key] + '</td>'
```

more style : http://cosicimiento.blogspot.com/2008/11/styling-excel-cells-with-mso-number.html

**Comment by jecovier** [comment]
@zgq456 sorry for the laaaaate comment, there is a new update that fix this issue casting all data as string
