### ISSUE TITLE
callbacks broken

### ISSUE THREAD

**Issue by ljm42** [jecovier/vue-json-excel#66]
I am having issues with my field callbacks since 0.2.86. With fields defined like this:

```
'Desc': 'description',
'DescLen': {
  field: 'description',
    callback: (value) => {
      return value.length;
  }
},
```

The `DescLen` field will return `[object Promise]` in the excel file.

I have tried a few things, but I don't have a good enough grasp on async / await to fix it. If I revert back to 0.2.85 then it works fine.

**Comment by jecovier** [comment]
Hello @ljm42, I solve this problem, please update to 0.2.89 and sorry for the problems

**Comment by ljm42** [comment]
Thanks @jecovier, the callbacks are working again :) 

But as part of the changes, line 105 changed to:
  `"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`

With the new mimetype, when I try to open the data.xls file directly from the browser, I get this error in Excel 2016:

`Excel cannot open the file 'data.xls-1.xlsx" because the file format or extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.`

I have to save the file first before opening it, then I get the usual warning:

`The file format and extension of 'data.xls' don't match. The file could be corrupted or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?`

If I change the mimetype in line 105 back to:
`  "application/vnd.ms-excel"`
then I am able to open directly after downloading again (although of course I get the usual warning)

Would you please revert this change in the mimetype?

**Comment by jecovier** [comment]
I'm gonna rollback the mimeType to the previous one. thank you so much for the help!
