### ISSUE TITLE
enhancement to callbacks

### ISSUE THREAD

**Issue by ljm42** [jecovier/vue-json-excel#67]
I'd like to request an enhancement to the callback function. Currently you can only pass a single field to the callback, I'd like to give it access to the entire row of data. 

This will open up more interesting options. Here is a simple example of how it could be used with the sample data:

```
'Location': {
  field: '_ALL_',
  callback: (value) => {
    return value.city + ", " + value.country;
  }
},
```

The change to implement this is very minor, just adding an extra if statement inside the getValue() function, 

```
if (field === "_ALL_")
  value = item;
else if (indexes.length > 1)
  value = this.getValueFromNestedItem(item, indexes);
else
  value = item[field];
```
What do you think?

**Comment by jecovier** [comment]
It's a great idea!... the only thing I don't like is the _ALL_ condition, because it's an arbitrary string and lost the ability to reach nested properties... maybe, return the last object you reach with the field value or if **field** it's undefined return the complete object

**Comment by ljm42** [comment]
I don't think we lose access to nested properties, inside the callback you could just reference `value.phone.mobile`, right?

But I agree about `"_ALL_"`. I like your idea of leaving the field undefined:

```
'Location': {
  callback: (value) => {
    return value.city + ", " + value.country;
  }
},
```

getValue() would just need a guard on the line that defines `indexes`:

```
getValue(key, item) {
  const field = typeof key === "object" ? key.field : key;
  let indexes = field ? field.split(".") : [];
  let value = this.defaultValue;

  if (!field)
	value = item;
  else if (indexes.length > 1)
	value = this.getValueFromNestedItem(item, indexes);
  else
	value = item[field];

  if (key.hasOwnProperty('callback'))
	value = this.getValueFromCallback(value, key.callback);

  return value;
},
```

**Comment by jecovier** [comment]
@ljm42 thanks for the code, It's added with a little change (interpreter problems ¬¬) but its functional now... documentation was added to README file. Thanks!

**Comment by ljm42** [comment]
Thanks! I like the way you explained it in the readme too

The mimetype has changed again though, can we change it back? Or make it an option somehow?

Also, in getValue(), I noticed that if you trigger this else statement:
```
 else
   value = item[field];
```
and don't have a callback, then `parseValue()` is never called on that value. Is that an issue?

**Comment by jecovier** [comment]
@ljm42 🤦‍♂️ sorry, I've changed it in my local, it won't change again... yeah! I add the parseValue, thanks!

**Comment by ljm42** [comment]
Sorry, the mimetype isn't quite right :)

This:
`  "vnd.ms-excel"`
should be:
`  "application/vnd.ms-excel"`

**Comment by jecovier** [comment]
🤦‍♂️ it's fixed now, thanks! 😃

**Comment by ljm42** [comment]
perfect, thanks!
