### ISSUE TITLE
Unable to bind to footer attribute

### ISSUE THREAD

**Issue by kedar2594** [jecovier/vue-json-excel#68]
Tried binding data to the footer attribute mentioned in the document but it is not processed.

//Vue code of json to excel
```
<download-excel class="pull-left btn btn-inverse waves-effect waves-light"
:title = "excel.excel_title"
:fields= "excel.excel_fields"
:data = "excel.excel_data"
footer = "Test" 
:name = "excel.filename">
EXCEL
</download-excel>
```

//data declared
```
excel:{
excel_data:[],
excel_title:'',
excel_footer:'',
filename:'',
excel_fields:{},
},
```
I have calculated and seen to i that the data is binded to excel object and then to the json to excel element except for footer(I tried binding initially and later gave the value directly in the element).

[Receipt Details(2018-10-17 - 2018-10-17).xls.zip](https://github.com/jecovier/vue-json-excel/files/2487289/Receipt.Details.2018-10-17.-.2018-10-17.xls.zip)

**Comment by jecovier** [comment]
@kedar2594 sorry for the late comment, It's working fine with new version. Please, update your dependency

**Comment by rafaelmagalhaes** [comment]
this is still not working
