### ISSUE TITLE
"null" in exported excel file

### ISSUE THREAD

**Issue by zhiyong80** [jecovier/vue-json-excel#7]
Hi, 

First of all thanks for putting together this work. After a little bit of tinkering, I was able to get it work.
Somehow the excel it generated has "null" in the first row, as in the following screenshot:
![image](https://user-images.githubusercontent.com/13650939/29751706-b8b1ac92-8b05-11e7-843b-2cc75a494289.png)

I assume this is something that can be passed from meta prop, but somehow the following meta didn't make a difference:

`        json_meta: [
          [{
            "key": "charset",
            "value": "utf-8"
          }],
          [{
            "key": "head",
            "value": "Raw Data"
          }]
        ]`

Am I missing anything?

Also on a side note, any chance to add a function to export simple CSV file?

Thanks again.

**Comment by zhegwood** [comment]
I have a feeling it's because metatags is being initialized as "null" then string concatenation after that.  I think initializing as '' instead of null will fix this issue.

**Comment by xdadda** [comment]
correct, replace null with ''
