### ISSUE TITLE
is it possible to change the sheet name ? by default it says {worksheet}

### ISSUE THREAD

**Issue by Davidriquelme** [jecovier/vue-json-excel#72]
as the the title says...
here is a screenshot: 

![image](https://user-images.githubusercontent.com/12628676/47829800-00873b80-dd68-11e8-9c39-f780bb8937d7.png)

thanks!

**Comment by Per4merKC** [comment]
@Davidriquelme I opened a pull request (#74) that should allow you to change the tab name.  It's a simple correction to the code if you want to manually apply the changes to your local code. 

Just look at the file diff to see the changes.

 I haven't seen any movement on this repo as far as pull request approval.

**Comment by Davidriquelme** [comment]
thanks a lot @Per4merKC , I'll wait a couple of days for the merge, if not will manually implemented.

**Comment by jecovier** [comment]
@Davidriquelme @Per4merKC sorry for the late merge, I was rather bussy this months... thanks for the feedback and the pull request 👍
