### ISSUE TITLE
False boolean values are not printed

### ISSUE THREAD

**Issue by larsvanhilten** [jecovier/vue-json-excel#76]
When a field returns a boolean with the value `false`, the output is empty.

For the following array: `[ { emailVerified: false }, { emailVerified: false }, { emailVerified: true }]`
The current output is:

```
| Email verified |
|                |
|                |
|      TRUE      |

```

The expected output is:
```
| Email verified |
|      FALSE     |
|      FALSE     |
|      TRUE      |

```

Current workaround is using `.toString()` method.

**Comment by jecovier** [comment]
@larsvanhilten thanks, the component is update and working fine
