### ISSUE TITLE
json id card number turned into weird format and losing the last charater

### ISSUE THREAD

**Issue by t0n1zz** [jecovier/vue-json-excel#79]
so i am exporting data of my registered user and there is id card number which contain 13 number ie.: 6112031505780002 and when i export it, in excel it show 6,11203E+15 and it is on general type of data and when i hover my cells into there, i see it is written as 611203150578000. so i lost the last charater... 

how to make all of these number just to be a string without any formating? i find this is quite anoying, and it also turn all other fields that only contain number and into something like this 6,11203E+xx (xx = number) if the fields contains number that more then specific digit, i think after 9 or 10 digit it will turned into that... 

how can i just get the plain string data?

**Comment by jecovier** [comment]
@t0n1zz there is a new update that fix this issue, thanks for the feedback

**Comment by t0n1zz** [comment]
hello do this new update already avaiable? i still getting this issue on version 0.2.98

**Comment by DorkasV** [comment]
same for me

**Comment by xuzongbao** [comment]
> hello do this new update already avaiable? i still getting this issue on version 0.2.98

has you resolved this problem？

**Comment by t0n1zz** [comment]
still having this issue with losing 1 number
