### ISSUE TITLE
Change name button

### ISSUE THREAD

**Issue by daviddsp** [jecovier/vue-json-excel#8]
Hi!
I have a problem, i need to change the name for button

Could help me, please?
![captura de pantalla de 2017-08-28 15-45-31](https://user-images.githubusercontent.com/2723396/29788155-fb540c4a-8c07-11e7-8053-cad44878307d.png)

**Comment by zhegwood** [comment]
You can pass in 'button_text' as a param.

**Comment by daviddsp** [comment]
Thanks @zhegwood

**Comment by jecovier** [comment]
@daviddsp hi, another option is to put an html code between the tag:
`<download-excel
	class   = "btn btn-default"
	:data   = "json_data"
	:fields = "json_fields"
	name    = "filename.xls">
       <i class="glyphicon glyphicon-file"></i> 
      Download an excel file 
</download-excel>`
