### ISSUE TITLE
value also included "="value" in each columns

### ISSUE THREAD

**Issue by AyemyaThi** [jecovier/vue-json-excel#87]
when using with type csv,
 <download-excel
	class   = "btn btn-default"
	:fetch   = "fetchData"
	:fields = "json_fields"
	type    = "csv"
	name    = "filename.xls">
	Download Excel (you can customize this with html code!)
</download-excel>
, every value included "=""Email - mike@example.com""","=""Mike""","=""2019-01-31 06:20:07""" in csv value column.

**Comment by jecovier** [comment]
hello @AyemyaThi... yeah that's a "fix" for MS Excel. but I realize that no every situation needs an Excel ready file... I think could be a prop to change that behavior 🤔, something like data-as-string and by default is false, so export a pure CSV file until you change it to true

**Comment by TheDude70** [comment]
Will there be a 'fix' for this soon? Having the same issue, and it is causing problems with users who need to import CSV data into other programs. Need the option to not have "=" included.

**Comment by nickcoats** [comment]
Hey @jecovier - following up here on your initial response. Any chance that this update is coming in the near future?

**Comment by wunderdojo** [comment]
Just ran into the same thing. I made the following change which is working for me, but I haven't done extensive testing. Generated a few files and opened in LibreCalc and Excel but I didn't play with lot of different data or anything so be forewarned. In JsonExcel.vue I changed line 208:

```
//let escapedCSV = '=\"' + item[key] + '\"'; // cast Numbers to string
          let escapedCSV = item[key].toString();`
```

**Comment by nillamahesh** [comment]
Hey @jecovier - Any update on the fix for this issue ?
