### ISSUE TITLE
customize excel output

### ISSUE THREAD

**Issue by t0n1zz** [jecovier/vue-json-excel#9]
hi is there any way to customize excel output? like in my table i have table that being grouped like this

```
<tbody>
   <tr>
        categories
   </tr>
   <tr>
       <td>Title</td>
       <td>Writer</td>
       <td>Published</td>
       <td>Created_at</td>
   </tr>
</tbody>
```

is it also posibble in excel to generate style like that?

and also i have hide column feature in my html, so i want if i convert json to excel it also remove json fields that is coresponding to those column that hide, ex: i hide writer column that mean in json the writer fields will be removed from there to so in excel it will just show exactly column that shown in html table

**Comment by jecovier** [comment]
Hi @t0n1zz , it's not possible to add styles to the output, but maybe it's possible to replicate that type of group, I will try tomorrow and post here the result :smiley: .
If you want to hide a column, I suggest  filter the data with underscore to erase the column before pass the json into the component. You can use the omit function in underscore to achieve that result. [http://underscorejs.org/#omit](http://underscorejs.org/#omit)

**Comment by jecovier** [comment]
@t0n1zz hi, the new version have a title prop that allows you to add a row above the data with a custom text.

`<download-excel
	class   = "btn btn-default"
        title = "THIS IS A TITLE"
	:data   = "json_data"
	:fields = "json_fields"
	name    = "filename.xls">

	Download Excel (you can customize this with html code!)

</download-excel>`

hope this help you

**Comment by t0n1zz** [comment]
hi i am sorry opening it again, but i already updated to version 0.0.7 and i put title="this is test title" but i don't find anything on the downloaded files....?

**Comment by jecovier** [comment]
Hi @t0n1zz the current version is the 0.1.8, I just update the repository, please try this new version. I add the option to pass an array as value of the title prop, so you can get more than one title, use as follow:
```html
<vueJsonExcel
      type = "csv"
      :title = '["DATA","title 2"]'
      name="data.csv"
      :data = "datos"
      :fields = "fields">
      CSV FILE
</vueJsonExcel>
```
If you only want a single title, just pass a string as value:
```html
<vueJsonExcel
      type = "csv"
      title = 'DATA TITLE'
      name="data.csv"
      :data = "datos"
      :fields = "fields">
      CSV FILE
</vueJsonExcel>
```
try the new version and tell me if this solve your problem.

**Comment by t0n1zz** [comment]
okay thank you so much... i see you have changed something too in json_fields in this new version but i can make it work... great works man.... looking forward for other awesome features... cheers
